server:
  port: 50002

spring:
  application:
    name: service-orders
  config:
    import: configserver:http://config-service:8888
  profiles:
    active: eureka-client-cloud,kafka-cloud,caffeine,jpa,feign-cloud,resourceserver-cloud,cloud,metrics-cloud