server:
  port: 50001

spring:
  application:
    name: service-products
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: caffeine,kafka,feign,resourceserver,jpa,eureka-client