server:
  port: 50004

spring:
  application:
    name: service-uploads
  config:
    import: configserver:http://config-service:8888
  profiles:
    active: kafka-cloud,resourceserver-cloud,eureka-client-cloud,cloud,metrics-cloud