server:
  port: 50000

spring:
  application:
    name: service-users
  config:
    import: configserver:http://config-service:8888
  profiles:
    active: caffeine,feign-cloud,jpa,resourceserver-cloud,eureka-client-cloud,cloud,metrics-cloud